# basic config options.
http-cache-dir: /cache/httpcache
organization: jetstack
project: tarmak
# Make sure approval-handler and blunderbuss run before submit-queue.
# Otherwise it's going to take an extra-cycle to detect the label change.
pr-mungers: approval-handler,blunderbuss,lgtm-after-commit,submit-queue,needs-rebase
state: open
token-file: /etc/secret-volume/token
period: 20s
repo-dir: /gitrepos
github-key-file: /etc/hook-secret-volume/secret

# status contexts options.
required-contexts: "tarmak-quick-verify"
required-retest-contexts: ""
# protected-branches-extra-contexts: "cla/linuxfoundation"

# submit-queue options.
protected-branches: "master"
nonblocking-jobs: ""
do-not-merge-milestones: ""
admin-port: 9999
context-url: https://tarmak.submit-queue.build-infra.jetstack.net
prow-url: https://prow.build-infra.jetstack.net
batch-enabled: true

# munger specific options.
label-file: "/gitrepos/tarmak/labels.yaml"

use-reviewers: true
gate-approved: true
gate-cla: false
